version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.4

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $PARAM_DOCKER_USERNAME/joke-api
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $PARAM_DOCKER_USERNAME/joke-api
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - '16.15'
                - '14.19'
                - '12.13'
          filters:
            branches:
              only:
                - main  

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - main  
      - heroku/deploy-via-git:
          app-name: joke-app-nat-circle  
          requires:
            - 'node/test'
            - 'node/run' 
          filters:
            branches:
              only:
                - deploy 
      - build-and-push:  
          requires:
            - 'node/test'
            - 'node/run'        
          filters:
            branches:
              only:
                - main